### ISSUE TITLE
Discord bot unresponsive

### ISSUE THREAD

**Issue by FlyCodeine** [gokberkkocak/tgtg-discord-bot#25]
Hi there.

I installed everything successfully and followed the readme perfectly.

Apparently, the bot is not responding to my commands, even if I see it online, and the console says it's successfully logged in.

Can you please help me?
![image](https://user-images.githubusercontent.com/75177920/175240980-093f2a55-45ce-4c63-90ff-58fb98e70699.png)

Thanks.

**Comment by gokberkkocak** [comment]
Hi,

Your bot is connected to the discord servers correctly and that's what the server info text is indicating.

If the bot is already in your server as you said (you can see it online when the program is running), I only can think as bot permissions issue. Did you generate an OAuth2 link using the correct permissions? I just invited the bot again with given scopes and permissions. It works fine.

Another possibility: are you using the generated v0.1.0 or did you compile the bot from the latest source. Some dependencies are updated in the latest commits and it might be the reason your program is unresponsive.

Unrelated note: your terminal doesn't print out the logs in a nice way. It's supposed to look like this:

![2022-06-23_13-49](https://user-images.githubusercontent.com/4727301/175303055-3c3253bd-7c4d-49b8-a912-ac7668b5683d.png)

I only tested the system on linux even though from rust it's possible to get windows executable. Are you using windows by any chance? If so, you might try WSL maybe to see any difference.

**Comment by FlyCodeine** [comment]
Thanks for your reply.

I created a new venv and installed all requirements.
Proceeded then to download the release 0.1.0, and as I am on windows, I tried to compile it.

This is the error I'm getting:
`Compiling tgtg-discord-bot v0.1.0 (C:\Users\xyz\Desktop\tgtg-discord-bot-0.1.0)
error: `DATABASE_URL` must be set to use query macros
  --> src\db.rs:31:28
   |
31 |           let optional_rec = sqlx::query!(
   |  ____________________________^
32 | |             r#"
33 | |                 SELECT active FROM channels WHERE channel_id = ?1
34 | |             "#,
35 | |             channel_id_str,
36 | |         )
   | |_________^
   |
   = note: this error originates in the macro `$crate::sqlx_macros::expand_query` (in Nightly builds, run with -Z macro-backtrace for more info)

error: `DATABASE_URL` must be set to use query macros
  --> src\db.rs:41:17
   |
41 | /                 sqlx::query!(
42 | |                     r#"
43 | |                         UPDATE channels SET latitude = ?1, longitude = ?2, radius = ?3, active = ?4 WHERE channel_id = ?5
44 | |                     "#,
...  |
49 | |                     channel_id_str,
50 | |                 )
   | |_________________^
   |
   = note: this error originates in the macro `$crate::sqlx_macros::expand_query` (in Nightly builds, run with -Z macro-backtrace for more info)

error: `DATABASE_URL` must be set to use query macros
  --> src\db.rs:55:17
   |
55 | /                 sqlx::query!(
56 | |                     r#"
57 | |                         INSERT INTO channels (channel_id, latitude, longitude, radius, active) VALUES (?1, ?2, ?3, ?4, ?5)
58 | |                     "#,
...  |
63 | |                     0,
64 | |                 )
   | |_________________^
   |
   = note: this error originates in the macro `$crate::sqlx_macros::expand_query` (in Nightly builds, run with -Z macro-backtrace for more info)

error: `DATABASE_URL` must be set to use query macros
  --> src\db.rs:75:28
   |
75 |           let optional_rec = sqlx::query!(
   |  ____________________________^
76 | |             r#"
77 | |                 SELECT active FROM channels WHERE channel_id = ?1
78 | |             "#,
79 | |             channel_id_str,
80 | |         )
   | |_________^
   |
   = note: this error originates in the macro `$crate::sqlx_macros::expand_query` (in Nightly builds, run with -Z macro-backtrace for more info)

error: `DATABASE_URL` must be set to use query macros
  --> src\db.rs:84:13
   |
84 | /             sqlx::query!(
85 | |                 r#"
86 | |                     UPDATE channels SET active = ?1 WHERE channel_id = ?2
87 | |                 "#,
88 | |                 active,
89 | |                 channel_id_str,
90 | |             )
   | |_____________^
   |
   = note: this error originates in the macro `$crate::sqlx_macros::expand_query` (in Nightly builds, run with -Z macro-backtrace for more info)

error: `DATABASE_URL` must be set to use query macros
   --> src\db.rs:104:23
    |
104 |           let records = sqlx::query!(
    |  _______________________^
105 | |             r#"
106 | |                 SELECT channel_id, latitude, longitude, radius, active FROM channels
107 | |             "#
108 | |         )
    | |_________^
    |
    = note: this error originates in the macro `$crate::sqlx_macros::expand_query` (in Nightly builds, run with -Z macro-backtrace for more info)

error: could not compile `tgtg-discord-bot` due to 6 previous errors`

I'll try now using WSL with the pre-compiled source.
Thanks!

**Comment by gokberkkocak** [comment]
You need to DATABASE_URL environment variable as README indicates.

```
sqlite3 bot.db < migrations/20220301134633_bot.sql 
export DATABASE_URL=sqlite:bot.db
```

if you are compiling yourself, i suggest using latest git version.

**Comment by gokberkkocak** [comment]
New discrod intent system might be causing this. #33 fixes it.
